### ISSUE TITLE
Security for this repo

### ISSUE THREAD

**Issue by tz-earl** [helpfulengineering/project-data-platform-ts#1]
We want security, permissions, and teams for this repo to be the same as the project-data-platform repo.

**Comment by Jbutler-helpful** [comment]
@devhawk this is resolved correct? The in tent was to the same structure for Groups as https://github.com/helpfulengineering/project-data-platform

**Comment by devhawk** [comment]
I am not an admin on this repo, so I can't be sure the perms match. But this repo has me, @Jbutler-helpful, @RobertLRead and @0x2b3bfa0 as "Admin"+ project-data-developer group as "Maintain"

**Comment by devhawk** [comment]
We don't have branch protection turned on , but not sure that's needed yet

**Comment by devhawk** [comment]
As an owner of the helpful engineering org, I was able to add myself as an admin of this repo and verify the permissions and compare the permissions between the repos. THe only difference is that `project-data` group has read access to the original project data repo. But since both repos are both public, that's the same permissions the anonymous user has. So I'm going to leave the permissions of this repo as is and close this issue
